### ISSUE TITLE
Can't start the Macro

### ISSUE THREAD

**Issue by bjornsol** [DualSPHysics/DesignSPHysics#11]
I've tried installing DesignSPHysics both with the installer and manually, but with each method I get the same error when I try to start the Macro in FreeCAD.
Readout from the Report View can be seen below.
`Traceback (most recent call last):
  File "C:/Users/bjornsol/AppData/Roaming/FreeCAD/Macro/DesignSPHysics.FCMacro", line 11, in <module>
    import DesignSPHysics
  File "C:\Users\bjornsol\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\DesignSPHysics.py", line 36, in <module>
    from ds_modules import utils, guiutils, xmlimporter, dsphwidgets
  File "C:\Users\bjornsol\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\ds_modules\utils.py", line 40, in <module>
    from future.utils import iteritems
<type 'exceptions.ImportError'>: No module named future.utils
`

**Comment by bjornsol** [comment]
Figured out my problem in the end. 
I commented out line #40 in utils.py and recompiled the dev version and it worked.
Any idea when inlet/outlet will be added btw?
