### ISSUE TITLE
libnglib.so not found

### ISSUE THREAD

**Issue by ebrov** [DualSPHysics/DesignSPHysics#79]
I just installed the DesignSPHysics macro in FreeCAD 0.18.4 and when trying to execute the macro, it throws the following error and does not open DesignSPHysics or any other warning popup:

```Traceback (most recent call last):
  File "/home/<user>/.FreeCAD/Macro/DesignSPHysics.FCMacro", line 16, in <module>
    from mod.main import boot  # pylint: disable=wrong-import-position
  File "/home/<user>/.FreeCAD/Mod/DesignSPHysics/mod/main.py", line 29, in <module>
    from mod.dataobjects.case import Case
  File "/home/<user>/.FreeCAD/Mod/DesignSPHysics/mod/dataobjects/case.py", line 18, in <module>
    from mod.dataobjects.executable_paths import ExecutablePaths
  File "/home/<user>/.FreeCAD/Mod/DesignSPHysics/mod/dataobjects/executable_paths.py", line 9, in <module>
    from mod.file_tools import get_saved_config_file, get_default_config_file
  File "/home/<user>/.FreeCAD/Mod/DesignSPHysics/mod/file_tools.py", line 26, in <module>
    import Fem
<class 'ImportError'>: libnglib.so: cannot open shared object file: No such file or directory
````
Code versions:
Ubuntu 20.04
FreeCAD 0.18.4
Python 3.8.2

Thanks for the help

**Comment by ebrov** [comment]
I have found the issue. For some reason, my Ubuntu 20.04 installation did not come loaded with the netgen library (https://packages.ubuntu.com/source/focal/netgen), which contains the libnglib.so shared library. Performing `sudo apt install netgen` then restarting FreeCAD and executing the DesignSPHysics macro worked perfectly.
